language: node_js

node_js:
  - 'node'

os:
  - windows
  - linux
  - osx

env:
  - BUILD_ENV=ci

branches:
  only:
    - master
    - test
    - /^greenkeeper/.*$/

install:
  - npm install

script:
  - npm run build
  - npm run test
  # - codecov -f coverage/*.json

# test:
#   - npm run test # 运行自动测试框架

after_success:
  - npm run coverage
